services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
        bind:
            $debug: '%kernel.debug%'
            $lockFile: '%kernel.project_dir%/var/manager_lock'

    Contao\ManagerApi\:
        resource: '../../*'
        exclude: '../../{Command,Controller,Resources,Tests}'

    Contao\ManagerApi\Command\:
        resource: '../../Command'
        public: true

    Contao\ManagerApi\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']


    ##############################
    #  Additional configuration  #
    ##############################

    Contao\ManagerApi\ApiKernel: '@kernel'

    Contao\ManagerApi\I18n\Translator:
        public: true

    locale_listener:
        class: Contao\ManagerApi\EventListener\LocaleListener

    Contao\ManagerApi\Task\TaskManager:
        arguments:
            - !tagged app.task
